packages:
  - packages/*
  - app

allowBuilds:
  '@reown/appkit': set this to true or false
  '@sentry/cli': set this to true or false
  '@stellar/stellar-sdk': set this to true or false
  bigint-buffer: set this to true or false
  blake-hash: set this to true or false
  bufferutil: set this to true or false
  esbuild: set this to true or false
  keccak: set this to true or false
  msw: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  tiny-secp256k1: set this to true or false
  unrs-resolver: set this to true or false
  usb: set this to true or false
  utf-8-validate: set this to true or false

onlyBuiltDependencies:
  - msw
